export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      name: "TechCorp Solutions",
      industry: "Technology",
      location: "San Francisco, CA",
      employees: 1250,
      founded: 2015,
      revenue: "$50M",
      website: "https://techcorp.com",
      description: "Leading provider of cloud-based enterprise solutions",
    },
    {
      id: 2,
      name: "Green Energy Inc",
      industry: "Energy",
      location: "Austin, TX",
      employees: 850,
      founded: 2018,
      revenue: "$35M",
      website: "https://greenenergy.com",
      description:
        "Renewable energy solutions for commercial and residential use",
    },
    {
      id: 3,
      name: "FinanceFlow",
      industry: "Finance",
      location: "New York, NY",
      employees: 2100,
      founded: 2012,
      revenue: "$120M",
      website: "https://financeflow.com",
      description: "Digital banking and financial services platform",
    },
    {
      id: 4,
      name: "HealthTech Innovations",
      industry: "Healthcare",
      location: "Boston, MA",
      employees: 650,
      founded: 2019,
      revenue: "$28M",
      website: "https://healthtech.com",
      description: "AI-powered healthcare diagnostics and patient management",
    },
    {
      id: 5,
      name: "EduLearn Platform",
      industry: "Education",
      location: "Seattle, WA",
      employees: 420,
      founded: 2020,
      revenue: "$15M",
      website: "https://edulearn.com",
      description: "Online learning platform for professional development",
    },
    {
      id: 6,
      name: "RetailMax",
      industry: "Retail",
      location: "Chicago, IL",
      employees: 3200,
      founded: 2008,
      revenue: "$200M",
      website: "https://retailmax.com",
      description: "E-commerce platform and retail management solutions",
    },
    {
      id: 7,
      name: "AutoDrive Systems",
      industry: "Automotive",
      location: "Detroit, MI",
      employees: 1800,
      founded: 2016,
      revenue: "$85M",
      website: "https://autodrive.com",
      description: "Autonomous vehicle technology and smart transportation",
    },
    {
      id: 8,
      name: "FoodChain Logistics",
      industry: "Logistics",
      location: "Atlanta, GA",
      employees: 950,
      founded: 2014,
      revenue: "$42M",
      website: "https://foodchain.com",
      description: "Supply chain management for food and beverage industry",
    },
    {
      id: 9,
      name: "CloudSecure",
      industry: "Technology",
      location: "San Jose, CA",
      employees: 580,
      founded: 2021,
      revenue: "$22M",
      website: "https://cloudsecure.com",
      description: "Cybersecurity solutions for cloud infrastructure",
    },
    {
      id: 10,
      name: "BioMed Research",
      industry: "Healthcare",
      location: "San Diego, CA",
      employees: 320,
      founded: 2017,
      revenue: "$18M",
      website: "https://biomed.com",
      description: "Biotechnology research and pharmaceutical development",
    },
    {
      id: 11,
      name: "Solar Dynamics",
      industry: "Energy",
      location: "Phoenix, AZ",
      employees: 740,
      founded: 2019,
      revenue: "$31M",
      website: "https://solardynamics.com",
      description: "Solar panel manufacturing and installation services",
    },
    {
      id: 12,
      name: "DataInsights Pro",
      industry: "Technology",
      location: "Denver, CO",
      employees: 290,
      founded: 2022,
      revenue: "$8M",
      website: "https://datainsights.com",
      description: "Business intelligence and data analytics platform",
    },
    {
      id: 13,
      name: "Urban Construction",
      industry: "Construction",
      location: "Miami, FL",
      employees: 1650,
      founded: 2010,
      revenue: "$95M",
      website: "https://urbanconstruction.com",
      description: "Commercial and residential construction services",
    },
    {
      id: 14,
      name: "AeroSpace Dynamics",
      industry: "Aerospace",
      location: "Houston, TX",
      employees: 2800,
      founded: 2005,
      revenue: "$180M",
      website: "https://aerospace.com",
      description: "Aerospace engineering and satellite technology",
    },
    {
      id: 15,
      name: "Fashion Forward",
      industry: "Fashion",
      location: "Los Angeles, CA",
      employees: 480,
      founded: 2018,
      revenue: "$25M",
      website: "https://fashionforward.com",
      description: "Sustainable fashion and apparel manufacturing",
    },
  ]);
}
